name: housing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - fastapi
  - uvicorn
  - pydantic
  - xgboost
  - lightgbm
  - boto3
  - requests
  - python-dotenv
  - ipykernel
  - pytest
  - httpx