name: ci-docker

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: sound-realty-mlops:ci
          load: true   # load image into the runner's Docker engine

      - name: Inspect image contents
        run: |
          docker run --rm -w /srv sound-realty-mlops:ci /bin/bash -lc "pwd && ls -la && echo '--- data ---' && ls -la data || true"

      - name: Train & test inside container
        run: |
          docker run --rm -w /srv -e PYTHONPATH=/srv sound-realty-mlops:ci micromamba run -n housing python -V
          docker run --rm -w /srv -e PYTHONPATH=/srv sound-realty-mlops:ci micromamba run -n housing python training/create_model.py
          docker run --rm -w /srv -e PYTHONPATH=/srv sound-realty-mlops:ci micromamba run -n housing pytest -q

